name: CI_ETL_Raizen

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Start containers
        run: docker-compose -f "docker-compose.yaml" up -d --build
        
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yaml" down
